ARCH = $(shell uname -m)

all:
	gcc -static -std=c99 -Os -Wall -IJacobiAlgorithm -o bin/JacobiAlgorithm-$(ARCH)-lnx \
	JacobiAlgorithm/main.c JacobiAlgorithm/matrix.c JacobiAlgorithm/jacobi.c JacobiAlgorithm/util.c \
	-lm
